[theme]
base="light"
primaryColor="#0063A6"      # Blau – Hauptfarbe
accentColor="#CC051C"       # Rot – Akzentfarbe
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F7F9FB"
textColor="#333333"
font="sans serif"

[server]
headless=true
port=8501
enableCORS=false
